### ISSUE TITLE
데비안8 64bit 에서 다솜 설치후 한글 입력을 할 수 없습니다.

### ISSUE THREAD

**Issue by madang01** [dasom-im/dasom-jeongeum#1]
데비안8 64bit 에서 다솜 설치후 한글 입력을 할 수 없습니다.

ibus 삭제후 "전체설정" -> "지역 및 언어" -> "입력 소스" 로 선택할 수 있는것이 2개 있지만
(1) "한국어" (2) "한국어(101키/104키호환) 
어떤것을 선택하던 영문만 입력 가능합니다.

또 im-config 로 다솜을 선택했다 하더라도 ibus 를 그대로 유지한체 "입력 소스"에 
"한국어(Hangul)" 이면 다솜이 아닌 ibus 상태입니다.

-------- uname -a 결과

```
madang01@madang01:~$ uname -a
Linux madang01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux
```

------ 다솜 설치 파일
dasom_1.0.1-debian-jessie_amd64.deb

**Comment by ghost** [comment]
테스트하고자 버추얼박스에 데비안 8.2.0-amd64 설치하였습니다. 데스크탑은 GNOME 환경으로 설치했습니다. dasom_1.0.1-debian-jessie_amd64.deb 파일 설치하였고,
im-config 설치 후에, im-config 하여 dasom 선택하고 로그아웃 / 로그인하니 작동되는 것을 확인하였습니다.
영문 키보드를 사용하신다면, dconf-editor 로 설정해야 하는 것이 있습니다.
https://forum.ubuntu-kr.org/viewtopic.php?f=2&t=28262&start=10#p125472
그리고 GNOME 환경을 사용하신다면
gnome-tweak-tool 로 확장에 Dasom Agent 을 ON 해주셔야 합니다.
그렇게 하면 한/영 상태를 확인할 수 있습니다.
그렇게 해도 작동이 되지 않으면,
gnome-terminal 실행하여

```
export | grep dasom
export | grep ibus
ps aux | grep dasom
```

결과를 올려주시기 바랍니다.

**Comment by ghost** [comment]
아울러 `cat .xinputrc` 결과도 올려주시기 바랍니다.

```
hodong@debian:~$ cat .xinputrc
# im-config(8) generated on Thu, 05 Nov 2015 22:28:12 +0900
run_im dasom
# im-config signature: e8fb43140a1bf118fa63a35bbbc4d390  -
```

**Comment by madang01** [comment]
안녕하세요. 현재 다솜 정상 작동합니다.

단지 제 행동에서 차이가 있다면 su - 로 root 계정에서 im-config 를 한것을 
일반 계정에서 im-config 로 입력기를 xim 에서 다솜으로 변경했을뿐입니다.

`export | grep dasom` 으로 아무것도 안 나온것이
일반 계정에서 im-config 로 입력기를 xim 에서 다솜으로 변경후

```
madang01@madang01:~$ export | grep dasom
declare -x GTK_IM_MODULE="dasom"
declare -x QT4_IM_MODULE="dasom"
```

이런 결과를 보여주네요.

추정하건데 im-config 가 개인 설정이라서 루트로 해도 
그 설정이 일반계정에는 영향을 주지 않은것 같습니다.
어디까지나 개인 추정입니다.

끝문자 버그 동작 안해서 기분좋네요 ^^
