### ISSUE TITLE
자모 입력 순서.

### ISSUE THREAD

**Issue by lockpick** [dasom-im/dasom-jeongeum#10]
한글 상태에서 두벌식 키보드로 p다음에 t를 누르면 "ㅔㅅ" 와 같이 나오기를 바라는 것이 일반적이지 않을까 합니다.
하지만 지금은 "세"로 나오네요.
어떻게 생각하시나요.

**Comment by ghost** [comment]
dasom-jeongeum 은 libhangul 에 기반하고 있습니다.

libhangul 에 있는 자동 순서 교정 해제에 관한 코드입니다.
https://github.com/choehwanjin/libhangul/blob/master/tools/hangul.c#L380
https://github.com/choehwanjin/libhangul/commit/9643fcb60d1291a079a4ff529da09556abc6030a

**Comment by ghost** [comment]
두벌식에만 해당되는 내용이고 세벌식에는 해당되지 않습니다.
`auto-correction` (자동 교정) 등의 적당한 이름으로 옵션을 제공하겠습니다.
기본값은 `false` 로 하겠습니다.
기본값(`false`)으로 `ㅔ + ㅅ = ㅔㅅ` 로 출력될 겁니다. 이 동작이 일반적인 동작입니다.

그러나 기존처럼 `ㅔ + ㅅ = 세` 로 출력하기 위해서는 `auto-correction` 을 `true` 로 설정해야 합니다.
조만간 코드를 작성하여 커밋하겠습니다.

저도 원하던 기능인데 감사합니다.
