### ISSUE TITLE
젠투 이빌드 만들었습니다. 앞으로 젠투 이빌드도 이 곳에서 제공되어 지면 좋겠습니다.

### ISSUE THREAD

**Issue by pA0k** [dasom-im/dasom-jeongeum#11]
우선 다솜을 최근에 알게 되어 올해 들어 설치해서 잘 사용하고 있습니다.
젠투 사용자이다 보니 잘 알지도 못 하는 이빌드 만들었어요.
의존성 부분 확인 부탁드리고요
단순 리눅스 사용자라 잘 몰라요
수정할 부분 수정해서 이 곳에서 제공되어 지면 좋겠다 싶어서 글 남겨봅니다.

http://www.gentoo-kr.org/news/421849
여기 제가 올려 놨어요

**Comment by ghost** [comment]
배포판 별 패키지는 각 배포판 프로젝트에 문의해주세요.
https://www.gentoo.org/

**Comment by sukso96100** [comment]
@pA0k 
https://bugs.gentoo.org/buglist.cgi?component=New%20Ebuilds&product=Gentoo%20Linux&resolution=---
여기로 들어가셔서 문의해 주시면 될 것 같네요.
