### ISSUE TITLE
Ctrl-Space를 강점하는 문제가 있습니다?

### ISSUE THREAD

**Issue by pA0k** [dasom-im/dasom-jeongeum#12]
기본 설정상태든 101-104호환이든 Ctrl-Space를 강점하는 군요
기본 키는 한글, 한자 키 그대로구요

**Comment by ghost** [comment]
무슨 말씀이신지 이해가 되지 않습니다. 구체적으로 작성해주세요.
2016. 1. 6. 09:22에 "pA0k" notifications@github.com님이 작성:

**Comment by pA0k** [comment]
Emacs에서 간단히 확인해 보실수 있습니다.
Ctrl-Space를 누르면 set-mark-command가 활성이 되야하는데
다솜을 기본 입력기로 설정하면 동작을 안하더군요
동일 환경 ibus에서는 발생하지 않는 문제입니다.

**Comment by ghost** [comment]
다솜 입력기의 언어 엔진 전환 키가 기본값으로 CTRL + SPACE 가 설정되어 있습니다.
`dconf-editor` 을 사용하여 다음처럼 해제하시면 됩니다.
![screenshot from 2016-01-06 20 16 36](https://cloud.githubusercontent.com/assets/9195462/12141558/d3fba234-b4b3-11e5-9079-76b894d279f4.png)

또는 터미널에서 다음의 명령으로 언어 엔진간 전환 단축키를 해제하실 수 있습니다.
`gsettings set org.freedesktop.Dasom hotkeys "['']"`

**Comment by pA0k** [comment]
정음 옵션만 들여다 보고 정작 다솜 옵션 볼 생각은 못 했네요
잘 동작합니다. 고맙습니다.
