### ISSUE TITLE
Qtcreator에서 Code Completing 기능이 동작하지 않습니다.

### ISSUE THREAD

**Issue by misari03** [dasom-im/dasom-jeongeum#15]
입력기를 다솜입력기로 선택하면 Qtcreator에서 "Code Completing" 기능이 동작하지 않습니다. ibus나 fcitx에
선 정상적으로 동작하는 것을 확인했습니다.

**Comment by ghost** [comment]
확인해봤는데 Qt 또는 qtcreator 쪽의 문제입니다.
ibus-hangul 또는 fcitx-hangul 은 영어 입력모드일 때 false 를 리턴합니다. 그래서 알파벳을 어플측에서 직접처리하는데 dasom-jeongeum은 영어 모드일 때 true를 리턴하고 그 알파벳을 commit 합니다. dasom-jeongeum은 정상적으로 작동하는데 어플에서 commit 받은 알파벳을 처리하지 못하여 그러한 현상이 나타나는 것입니다.
ibus, fcitx, dasom 에서 한글 모드일 때 3종의 입력기가 모두 true 를 리턴할 것이므로 마찬가지 사유로 ibus, fcitx, dasom 에서 자동 완성 기능이 작동하지 않을 것으로 추정됩니다. qtcreator 프로젝트에 버그리포트 보내주세요. 화상키보드로도 시도해보세요. 제 예상대로라면 화상키보드로 영문 입력할 때에도 자동 완성 기능이 작동하지 않을 것 같습니다.
dasom-jeongeum 에 회피 코드를 넣을 수는 있지만, 지금은 고려하지 않겠습니다.

**Comment by misari03** [comment]
고맙습니다.

**Comment by ghost** [comment]
이러한 어플 이슈 때문에 땜빵 입력기라고 오해하는 사람들이 있으니 이슈를 닫아주세요.

**Comment by ghost** [comment]
회피 코드를 적용하였습니다.

https://github.com/dasom-im/dasom-jeongeum/commit/0eb6e0f6a06526253c4b9a13a0112c7ad3a72bf4
https://github.com/dasom-im/dasom-jeongeum/commit/ec12b979f1de4a560d23afb9c3f6d5018935f099

어플 버그를 회피하는 코드(workaround code)를 dasom 에 넣는 이유는 어플을 당장 사용해야 하는데  어플 버그가 고쳐지고 릴리즈되어 배포판에 탑재되기까지 시간이 걸리기 때문입니다.

입력기에서 어플 버그를 회피할 수 있는 방법은 극히 제한되어 있기 때문에 ibus, fcitx, uim, dasom 등의 입력기에서 어플 버그를 근본적으로 해결하는 것은 불가능합니다.

따라서 어플 버그에 대한 근본적인 해결은 해당 어플 프로젝트에서 다루어져야 합니다.

다솜 프로젝트, 다솜 팀원 및 다솜 개발자는 응용 어플리케이션에 대한 보증 책임이 없습니다. 또한 다솜 입력기에 대한 보증 책임이 없습니다.

감사합니다.
