### ISSUE TITLE
debian8 iceweasel 에서 kldp 비밀번호 입력이 안됩니다.

### ISSUE THREAD

**Issue by madang01** [dasom-im/dasom-jeongeum#3]
debian8 iceweasel 에서 kldp 비밀호번 입력이 안됩니다.
그래서 현재 나비(?) 로 변경후 로그아웃해서 글을 쓰고 있습니다.
개인적으로 다솜인지 나비인지 구별이 어렵지만
어찌되었든 im-config 에서는 나비이기에
나비 상태에서는 kldp 사이트 비밀번호 입력은 잘 됩니다.

버그인지 확인 부탁드립니다.

**Comment by ghost** [comment]
해당 버그는 https://github.com/dasom-im/dasom/commit/a63e8a13d6a532f000139e0af28823d76b445db0 에서 고쳤습니다.
불편하실텐데 조만간 릴리즈를 준비하도록 하겠습니다.

**Comment by ghost** [comment]
This issue was moved to dasom-im/dasom#28
