### ISSUE TITLE
Komodo Edit, 한국어 입력이 이상해지는 문제.

### ISSUE THREAD

**Issue by ghost** [dasom-im/dasom-jeongeum#5]
_From @nemonein on December 12, 2015 7:48_

안녕하세요.
우분투 14.04(64bit) 사용 중이고, 다솜은 PPA 최신판 사용중입니다.
Komodo Edit(http://komodoide.com/komodo-edit/) 에서 한국어 입력이 이상하게 되는 현상이 있습니다.

Komodo Edit 에서 '동해물과 백두산이 마르고 닳도록' 을 입력해보면..
'동ㅎ매ㅜㄹㄱ 백ㄷ수ㅏㄴㅇ 마르 닳ㄷ로ㅗ'  이런 식으로 입력이 됩니다.

이것도 Komodo Edit 의 문제가 아닐까요?
iBus, Fcitx, Uim, 다솜 모두 입력이 제대로 되지 않습니다. 유일하게 Scim 만 제대로 됩니다.
제 블로그에 쓴 글을 참고해주시면 고맙겠습니다.
http://nemonein.egloos.com/5287283

....
이것들과 더불어 대략 8개 정도 에디터에 대해 테스트를 해봤는데요. (http://nemonein.egloos.com/5278522)
이 글 바로 전에 보고했던 Sublime Text 3 과 이것을 제외하면 다솜은 잘 작동하는 것 같습니다. iBus 에서 치명적인 문제를 보이는 Notepadqq 에서도 다솜은 잘 작동하네요. 멋집니다~!
그리고 고맙습니다!

Komodo Edit 도 한번 살펴봐주시면 좋겠네요.

_Copied from original issue: dasom-im/dasom#41_

**Comment by ghost** [comment]
Komodo Edit 를 확인해봤는데, 다솜 버그가 아닙니다.
`동ㅎ매ㅜㄹㄱ 백ㄷ수ㅏㄴㅇ 마르 닳ㄷ로ㅗ` 왜 이런 현상이 발생되냐면,
`동`이 조합 중일 때 `ㅎ`을 누르면 `동`이 commit 됩니다.
그런데 Komodo Edit 가 commit callback 내에 reset() 을 호출하여 입력기가 reset 되어 조합 중인 `ㅎ`이 commit 되는 것입니다.
그 버그를 회피하는 코드를 작성할 수는 있지만, 그러한 방법은 좋지 않은 방법입니다. Komodo Edit 측에 버그 보고를 하는 것이 좋겠습니다.

**Comment by ghost** [comment]
`avoid-reset-in-commit-callback` 옵션을 제공합니다. 기본값으로 `true`로 설정했습니다.
Komodo Edit, github 웹 편집기에서 오작동하던 어플 버그를 회피합니다.

**Comment by nemonein** [comment]
Komodo 에서 잘 되는 것을 확인했습니다.
고맙습니다.
