### ISSUE TITLE
Wine : Total Commander 에서 키패드 + 문제.

### ISSUE THREAD

**Issue by ghost** [dasom-im/dasom-jeongeum#8]
_From @nemonein on December 16, 2015 14:7_

Wine/Total Commander(파일 매니저; www.totalcmd.com) 에서, 파일을 한꺼번에 선택할 수 있는 키로 키패드의 '+' (키보드 오른쪽의 숫자키에 있는 +)를 사용하고 있습니다. 
'+' 를 누르면 아래 그림처럼 그룹 선택창이 나와야 합니다.
![tc-group](https://cloud.githubusercontent.com/assets/5688288/11842802/672ff03a-a449-11e5-8d5f-eb83ea3ab85d.png)
다솜의 경우 아무런 반응이 없습니다.
iBus, Fcitx, 나비 모두 정상 작동합니다.

늦게까지 고생하시네요. 정말 고맙습니다!
이것도 확인 부탁드립니다.

_Copied from original issue: dasom-im/dasom#43_

**Comment by ghost** [comment]
_From @igxactly on December 18, 2015 9:37_

비슷한 문제로 추정됩니다만, Kate에서 VI 모드를 사용하면 정상적으로 입력이 안 됩니다.

**Comment by ghost** [comment]
kate는 qt 어플입니다. https://github.com/dasom-im/dasom-qt/issues 에 이슈를 작성해주세요.

**Comment by ghost** [comment]
확인해보았는데 다솜 버그가 아닙니다. ibus, fcitx, nabi 에서 `+` 가 먹히는 이유는 한글 엔진에서 `+` 를 받으면 이를 소비하지 않기 때문에 `FALSE` 를 반환하고 `IMForwardEvent()`로 이벤트를 돌려 보내는데,
다솜의 경우, 한글 엔진(dasom-jeongeum)에서 `+` 를 소비하기 때문에 `TRUE`를 반환합니다. 아울러  `IMForwardEvent()`로 이벤트를 돌려 보내지 않습니다. 정상적인 동작입니다.

WINE/Total Commander 의 왼쪽에 파일 나오는 창을 클릭할 경우 WINE/Total Commander 가 `XNFocusWindow` 또는 `XNClientWindow` 를 `NULL` (0 값)로 세팅해야 될 것 같습니다. 아니면 키 이벤트를 입력기로 보내지 말고 WINE/Total Commander 가 직접 처리해야 할 것 같습니다.

이 문제는 WINE 또는 Total Commander 의 문제입니다.
다솜에서 이를 회피할 수 있는 방법이 있습니다. ibus, fcitx, nabi 에 있는 한글 엔진 모듈처럼 dasom-jeongeum 이 키패드의 키값을 소비하지 않도록 변경하는 방법이 있으나 지금은 적용하지 않겠습니다.
xkb 도입 이후 다시 고려하겠습니다.

**Comment by ghost** [comment]
Added workaround-for-wine https://github.com/dasom-im/dasom-jeongeum/commit/1d72858ba1c92e398e7b4f2fd4df36b551d63f61

**Comment by nemonein** [comment]
Workaround 이후 잘 작동합니다.
고맙습니다.
