### ISSUE TITLE
깔리지가 않아요.

### ISSUE THREAD

**Issue by iyagicom** [dasom-im/dasom-jeongeum#9]
다솜까는건 정말로 어렵네요.
우분투 15.10 입니다.

아래와 같이 에러 나와요

root@iyagi:/home/iyagi/다운로드/dasom-jeongeum-master# ./autogen.sh 
autoreconf not found, please install autoconf package
root@iyagi:/home/iyagi/다운로드/dasom-jeongeum-master# apt-get install autoconf
패키지 목록을 읽는 중입니다... 완료
의존성 트리를 만드는 중입니다  
상태 정보를 읽는 중입니다... 완료
다음 패키지를 더 설치할 것입니다:
  automake autotools-dev libsigsegv2 m4
제안하는 패키지:
  autoconf-archive gnu-standards autoconf-doc libtool
다음 새 패키지를 설치할 것입니다:
  autoconf automake autotools-dev libsigsegv2 m4
0개 업그레이드, 5개 새로 설치, 0개 제거 및 0개 업그레이드 안 함.
1,079 k바이트 아카이브를 받아야 합니다.
이 작업 후 4,048 k바이트의 디스크 공간을 더 사용하게 됩니다.
계속 하시겠습니까? [Y/n] y
받기:1 http://kr.archive.ubuntu.com/ubuntu/ wily/main libsigsegv2 amd64 2.10-4 [14.1 kB]
받기:2 http://kr.archive.ubuntu.com/ubuntu/ wily/main m4 amd64 1.4.17-4 [193 kB]
받기:3 http://kr.archive.ubuntu.com/ubuntu/ wily/main autoconf all 2.69-8 [321 kB]
받기:4 http://kr.archive.ubuntu.com/ubuntu/ wily/main autotools-dev all 20140911.1 [39.6 kB]
받기:5 http://kr.archive.ubuntu.com/ubuntu/ wily/main automake all 1:1.15-1ubuntu1 [511 kB]
내려받기 1,079 k바이트, 소요시간 2초 (451 k바이트/초)
Selecting previously unselected package libsigsegv2:amd64.
(데이터베이스 읽는중 ...현재 209160개의 파일과 디렉터리가 설치되어 있습니다.)
Preparing to unpack .../libsigsegv2_2.10-4_amd64.deb ...
Unpacking libsigsegv2:amd64 (2.10-4) ...
Selecting previously unselected package m4.
Preparing to unpack .../archives/m4_1.4.17-4_amd64.deb ...
Unpacking m4 (1.4.17-4) ...
Selecting previously unselected package autoconf.
Preparing to unpack .../autoconf_2.69-8_all.deb ...
Unpacking autoconf (2.69-8) ...
Selecting previously unselected package autotools-dev.
Preparing to unpack .../autotools-dev_20140911.1_all.deb ...
Unpacking autotools-dev (20140911.1) ...
Selecting previously unselected package automake.
Preparing to unpack .../automake_1%3a1.15-1ubuntu1_all.deb ...
Unpacking automake (1:1.15-1ubuntu1) ...
Processing triggers for man-db (2.7.4-1) ...
Processing triggers for install-info (6.0.0.dfsg.1-3) ...
Processing triggers for doc-base (0.10.6) ...
Processing 1 added doc-base file...
libsigsegv2:amd64 (2.10-4) 설정하는 중입니다 ...
m4 (1.4.17-4) 설정하는 중입니다 ...
autoconf (2.69-8) 설정하는 중입니다 ...
autotools-dev (20140911.1) 설정하는 중입니다 ...
automake (1:1.15-1ubuntu1) 설정하는 중입니다 ...
update-alternatives: using /usr/bin/automake-1.15 to provide /usr/bin/automake (automake) in auto mode
Processing triggers for libc-bin (2.21-0ubuntu4) ...

root@iyagi:/home/iyagi/다운로드/dasom-jeongeum-master# ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:14: installing 'build-aux/ar-lib'
configure.ac:14: installing 'build-aux/compile'
configure.ac:10: installing 'build-aux/install-sh'
configure.ac:10: installing 'build-aux/missing'
Makefile.am: installing './INSTALL'
src/Makefile.am:2: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:2:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:2:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:2:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:2:   its definition is in aclocal's search path.
src/Makefile.am: installing 'build-aux/depcomp'
autoreconf: automake failed with exit status: 1
root@iyagi:/home/iyagi/다운로드/dasom-jeongeum-master# make
make: **\* 타겟이 지정되지 않았고 메이크파일이 없습니다.  멈춤.

**Comment by ghost** [comment]
libtool 을 설치하신 후 다시 일반 사용자 권한으로 ./autogen.sh 를 실행하세요.
`sudo apt-get install libtool`

아래 문서를 참고하세요.
https://wiki.ubuntu-kr.org/index.php/Dasom

**Comment by ghost** [comment]
우분투 포럼 사람들은 이제 PPA 이런거 가지고 시비거나요?
설치 문의 자꾸 해서 기껏 만들어줬더니... 한다는 소리가 이런 건가요?

```
dasom-im PPA 까는 방법?

https://launchpad.net/~dasom/+archive/ubuntu/ppa 있는 링크로 깔려고 하는데 뭔가 다른것 같아요.
deb http://ppa.launchpad.net/dasom/ppa/ubuntu wily main
deb-src http://ppa.launchpad.net/dasom/ppa/ubuntu wily main

0.AD PPA 경우 아래와 같은데요

sudo add-apt-repository ppa:wfg/0ad
sudo apt-get update
sudo apt-get install 0ad
```

그래서 그게 어쨌다는 건가요?
dasom PPA 주소를 `ppa:dasom/dasom` 이렇게 바꾸라고 압력넣는 건가요?

그런 식으로 하시면 PPA 서비스 없애버리겠습니다.

**Comment by janghe11** [comment]
확인 결과, 위와 같은 사람(iyagicom)은 우분투 한국 커뮤니티 내의 존재하는 회원이 아닙니다.

**Comment by ghost** [comment]
1111 이분 아닌가요?

**Comment by ghost** [comment]
과거... 제가 cogniti 란 아이디로 우분투 포럼에서 활동했었습니다.
그때 s님과 d님이 절 공격했고 기분나빠서 탈퇴했습니다.
d님은 libhwp 사건 관련자입니다.

그 후 저는 hodong 란 아이디로 우분투 포럼에서 활동하고 있고
s님이 다솜 프로젝트에 반복적으로 시비를 걸기 시작했었습니다. 여기서부터 촉발된 사건입니다.
저는 몇몇 회원님의 문제로 보지 않습니다.
libhwp 사건으로 알 수 있듯이 한국 우분투 커뮤니티의 문제로 보고 있습니다.
지금도 친목 모임 식으로 운영이 되는지는 모르겠으나, 만약 그렇다면 친목 모임.. 이런 것 모두 근절되어야 할 겁니다. 특히... 세미나 후 친목 모임 성격의 뒷풀이, 술자리.

앞으로도 계속하여 반복적으로 이러한 일이 반복된다면,
한국 우분투 커뮤니티의 문제점을 상세히 분석하여 정보통신산업진흥원에 한국 우분투 커뮤니티 활동 및 행사 지원에 대해 정식으로 문제 제기를 하겠습니다.

**Comment by janghe11** [comment]
네 iyagicom 이라는 분은 포럼 조회결과 저희 회원이 아닙니다.
고생 많으시네요.

**Comment by janghe11** [comment]
그건 개인 문제 같고, 말씀하신 s님은 저희가 2년 제명을 했는데 뭘 더 어떻게 해달라는건지 모르겠네요.
저희는 친목 및 뒤풀이의 경우 원하는 사람만 하고 있으며, 회계처리 또한 하고 있습니다.
장소 제공에 대한 정부 보고서도 계속 쓰고 있구요.
어떤 점을 문제제기 하신다는 건지 잘 모르겠습니다.

뭐, 지속적인 저러한 이슈에 대해서 커뮤니티 밖에서는 제가 어떻게 도와드릴 수 있는 일이 없네요.
개인적인 원한은 두분이서 잘 푸시기 바라겠습니다.

감사합니다.

**Comment by ghost** [comment]
아.. 그렇군요.. 잘 알겠습니다.

**Comment by janghe11** [comment]
sudo add-apt-repository ppa:/dasom/ppa
sudo apt-get update
까지 하셨다면
다솜 관련 패키지를 전부 다 설치 해주셔야 합니다.

sudo apt-get install dasom dasom-gtk dasom-qt dasom-jeongeum

오늘 질답게시판의 글을 읽어보았습니다.
제가 보기엔 정말로 모르셔서 질문 하신거 같은데, 포럼에 있는 글도 현재 똑같이 답변 드렸고 앞으로 우분투나 리눅스 관련 질문은 https://ask.ubuntu-kr.org/ 로 가셔서 질문해달라고 적어주시면 github에서 dasom 관련 이슈만 들어올겁니다.
